django_authgroupex/urls.py
from django.conf.urls import patterns, url

from . import conf
from . import views


urlpatterns = patterns('',
    url(r'^$', views.AuthGroupeXUniqueView().login_view, name='login'),
)


config = conf.AuthGroupeXConf()

if config.FAKE:
    urlpatterns += patterns('django_authgroupex.fake.views',
        url(r'^fake/validate/$', 'endpoint', name='fake_endpoint'),
        url(r'^fake/fill/$', 'login_view', name='fake_fill'),
    )

django_authgroupex_dev/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()
# Use authgroupex login on admin site
admin.site.login_template = 'authgroupex/admin_login.html'

urlpatterns = patterns('',
    url(r'^$', 'django_authgroupex_dev.devsite.views.home', name='home'),
    url(r'^xorgauth/', include('django_authgroupex.urls', namespace='authgroupex')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/', 'django_authgroupex_dev.devsite.views.logout', name='logout'),
)

django_authgroupex_dev/devsite/views.py
from django.contrib import auth
from django.contrib import messages
from django.core.urlresolvers import reverse
from django import http
from django import shortcuts


def home(request):
    return shortcuts.render(request, 'devsite/home.html', {
        'user': request.user,
    })

def logout(request):
    auth.logout(request)
    messages.success(request, u"Logout successful.")
    return http.HttpResponseRedirect(reverse('home'))

django_authgroupex_dev/devsite/templates/devsite/home.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
{% if user.is_authenticated %}
    <h3>Welcome, {{ user.get_full_name }}</h3>
    <p><a href="{% url 'logout' %}">Log out </a></p>
    <table border="1">
        <tr>
              <th colspan="2">Account fields</th>
              <th>Description</th>
        </tr>
        <tr>
            <td>username</td>
            <td>{{ user.username }}</td>
            <td>Forlife identifier</td>
        </tr>
        <tr>
            <td>first_name</td>
            <td>{{ user.first_name }}</td>
            <td>First name</td>
        </tr>
            <td>last_name</td>
            <td>{{ user.last_name }}</td>
            <td>Last name</td>
        </tr>
        </tr>
            <td>email</td>
            <td>{{ user.email }}</td>
            <td>Email address</td>
        </tr>
        </tr>
            <td>is_superuser</td>
            <td>{% if user.is_superuser %}True{% else %}False{% endif %}</td>
            <td>Global admin</td>
        </tr>
        </tr>
            <td>is_staff</td>
            <td>{% if user.is_staff %}True{% else %}False{% endif %}</td>
            <td>Group admin</td>
        </tr>
        </tr>
            <td>is_active</td>
            <td>{% if user.is_active %}True{% else %}False{% endif %}</td>
            <td>Alive</td>
        </tr>
    </table>
{% else %}
    <h3>Authenticate</h3>
        <p><a href="{% url 'authgroupex:login' %}?next=/" />Connect through X.org</a></p>
{% endif %}
{% endblock %}